package manager;

import java.sql.*;
import java.util.Scanner;
import java.time.*;
import java.time.temporal.ChronoUnit;

import errors.NotFoundException;
import errors.InvalidDateException;
import errors.ISBNException;

public class CheckoutManager extends Manager {

	/**
	 * Constructor to initialize the checkout manager by setting the super class variables for the database connection
	 */
	public CheckoutManager(Connection conn, Statement stmt) {
		super(conn, stmt);
	}

	/**
	 * Method to display the menu options for the checkout manager and handle user input
	 * User can choose to create a new checkout, return a book, update a checkout,
	 * search through the checkouts, view all the checkouts, or return to the main menu
	 * If the user enters an invalid input, display an error message and prompt them to enter a valid input (loop until they do)
	 */
	@Override
	public void displayMenu() {
		// Variable to hold the user's menu input and initialize the keyboard scanner created in the method abstract class
		int menuChoiceInt = 0;
		keyboard = new Scanner(System.in);
		// Loop menu options until the user chooses to exit the checkout manager
		while(menuChoiceInt != 6) {
			System.out.println("Checkout Manager Menu:");
			System.out.println("1) New Checkout");
			System.out.println("2) Return Book");
			System.out.println("3) Update Checkout");
			System.out.println("4) Search Checkouts");
			System.out.println("5) View All Checkouts");
			System.out.println("6) Return to Main Menu");
			menuChoiceInt = Integer.parseInt(keyboard.nextLine());
			switch(menuChoiceInt) {
				case 1:
					add();
					break;
				case 2:
					remove();
					break;
				case 3:
					update();
					break;
				case 4:
					search();
					break;
				case 5:
					viewAll();
					break;
				case 6:
					System.out.println("Returning to Main Menu...");
					break;
				default:
					System.out.println("Invalid input. Please enter a number between 1 and 6.");
			}
		}
	}

	/**
	 * Method to create a new checkout in the database
	 * checkout id will be automatically generated by the database, so it is not included as a parameter in the method
	 * the checkout date will be set to the current date
	 * the checkout return date will be set to 7 days after the checkout date
	 * the book ISBN and member ID will be provided by the user and must already exist in the database in order to create a new checkout
	 */
	@Override
	public void add() {		
		try{
			// check if the member ID provided by the user exists in the database
			String sqlStmt = "SELECT * FROM MEMBER WHERE MEMBERID = ?";

			System.out.println("Enter the Member ID of the member checking out the book:");
			String memberID = keyboard.nextLine();

			PreparedStatement stmt = conn.prepareStatement(sqlStmt);
			stmt.setString(1, memberID);
			ResultSet resultSet = stmt.executeQuery();
			if (!resultSet.next()) {
				throw new NotFoundException("Member not found. Please enter a valid Member ID.");
			} else {
				// check if the book ISBN provided by the user exists in the database
				sqlStmt = "SELECT * FROM BOOK WHERE ISBN = ?";
	
				System.out.println("Enter the ISBN of the book being checked out:");
				String bookISBN = keyboard.nextLine();
				// book ISBN validation, ISBN must be 13 characters long and can only contain numbers
				if (!bookISBN.matches("\\d{13}")) {
					throw new ISBNException("Invalid ISBN. ISBN must be 13 characters long and only contain numeric characters.");
				}
	
				/**
				 * There might be a bug here with isbn not being a long.
				 */
				
				stmt = conn.prepareStatement(sqlStmt);
				stmt.setString(1, bookISBN);
				resultSet = stmt.executeQuery();
				if (!resultSet.next()) {
					throw new NotFoundException("Book not found. Please enter a valid ISBN.");
				} else {
					// if the member ID and book ISBN both exist in the database, create a new checkout with the current date as the checkout date and the return date set to 7 days after the checkout date
					sqlStmt = "INSERT INTO CHECKOUT (CHECKOUTDATE, RETURNDATE, MEMBERID, BOOKISBN) VALUES (?, ?, ?, ?)";
					stmt = conn.prepareStatement(sqlStmt);
					stmt.setString(1, LocalDate.now().toString());
					stmt.setString(2, LocalDate.now().plusDays(7).toString());
					stmt.setString(3, memberID);
					stmt.setString(4, bookISBN);
					stmt.executeUpdate();
					System.out.println("Checkout created successfully.");
				}
			}
		} catch (SQLException e) {
			System.out.println(e.getMessage());
			return;
		} catch (NotFoundException e) {
			System.out.println(e.getMessage());
			return;
		} catch (ISBNException e) {
			System.out.println(e.getMessage());
		}
	}

	/**
	 * Method to return a book and remove the checkout from the database
	 * User provides the checkout ID of the book being returned
	 * If the checkout ID is not found in the database display error message and return to the menu
	 * if checkout ID is found get the checkout return date
	 * compare the return date to the current date to determine if the book is being returned late or not
	 * if the book is returned late charge the user 5$ per day late
	 * if the book is returned on time display a message saying the book was returned on time and there is no late fee
	 * remove the checkout from the database after the book is returned
	 */
	@Override
	public void remove() {
		System.out.println("Enter the Checkout ID of the book being returned:");
		String checkoutIDStr = keyboard.nextLine();
		// validate that the checkout ID is a number
		while (!checkoutIDStr.matches("\\d+")) {
			System.out.println("Invalid input. Please enter a valid Checkout ID.");
			checkoutIDStr = keyboard.nextLine();
		}
		int checkoutIDInt = Integer.parseInt(checkoutIDStr);

		String sqlStmt = "SELECT * FROM CHECKOUT WHERE CHECKOUTID = ?";
		// Verify that the book exists before attempting to delete it
		try {
			PreparedStatement stmt = conn.prepareStatement(sqlStmt);
			stmt.setInt(1, checkoutIDInt);
			ResultSet resultSet = stmt.executeQuery();
			if (!resultSet.next()) {
				throw new NotFoundException("Checkout not found. Please enter a valid Checkout ID.");
			} else {
				// get the return date and compare it to the current date
				LocalDate returnDate = LocalDate.parse(resultSet.getString("ReturnDate"));

				LocalDate currentDate = LocalDate.now();
				if (currentDate.isAfter(returnDate)) {
					long daysLate = ChronoUnit.DAYS.between(returnDate, currentDate);
					double lateFee = daysLate * 5;
					System.out.println("The book is being returned is overdue. The late fee is: $" + lateFee + "\n");

					// Delete the checkout from the database
					sqlStmt = "DELETE FROM CHECKOUT WHERE CHECKOUTID = ?";
					stmt = conn.prepareStatement(sqlStmt);
					stmt.setInt(1, checkoutIDInt);
					stmt.executeUpdate();
				} else {
					System.out.println("Book returned on time. No late fee.\n");

					// Delete the checkout from the database
					sqlStmt = "DELETE FROM CHECKOUT WHERE CHECKOUTID = ?";
					stmt = conn.prepareStatement(sqlStmt);
					stmt.setInt(1, checkoutIDInt);
					stmt.executeUpdate();
				}
			}
		} catch (SQLException e) {
			System.out.println(e.getMessage());
			return;
		} catch (NotFoundException e) {
			System.out.println(e.getMessage());
			return;
		}
	}

	/**
	 * Method to update the information of an existing checkout in the database
	 * User provides the checkout ID of the checkout they want to update
	 * If the checkout ID is not found in the database display error message and return to the menu
	 * if the checkout ID is found display the current checkout information
	 * User can then choose to update the checkout date, return date, member ID, or book ISBN
	 * if the user decides to update the member ID or book ISBN verify that the new ID and ISBN exist in the database
	 * if the new member ID or book ISBN do not exist display an error message and return to the menu
	 */
	@Override
	public void update() {
		try{
			System.out.println("Enter the Checkout ID of the checkout you want to update:");
			int checkoutID = Integer.parseInt(keyboard.nextLine());

			String sqlStmt = "SELECT * FROM CHECKOUT WHERE CHECKOUTID = ?";
			PreparedStatement stmt = conn.prepareStatement(sqlStmt);
			stmt.setInt(1, checkoutID);
			ResultSet resultSet = stmt.executeQuery();
			if (!resultSet.next()) {
				throw new NotFoundException("Checkout not found. Please enter a valid Checkout ID.");
			} else {
				// display current information
				System.out.println(String.format("Checkout ID: %s Checkout Date: %s Return Date: %s Member ID: %s Book ISBN: %s\n", resultSet.getInt("CheckoutID"), resultSet.getString("CheckoutDate"), resultSet.getString("ReturnDate"), resultSet.getString("MemberID"), resultSet.getString("BookISBN")));
				System.out.println("Enter the number corresponding to the information you want to update: \n1) Checkout Date \n2) Return Date \n3) Member ID \n4) Book ISBN");
				
				// get a valid menu choice from the user
				int updateChoiceInt = 0;
				while (updateChoiceInt < 1 || updateChoiceInt > 4) {
					String updateChoice = keyboard.nextLine();
					if (!updateChoice.matches("[1-4]")) {
						System.out.println("Invalid input. Please enter a number between 1 and 4.");
						continue;
					} else {
						updateChoiceInt = Integer.parseInt(updateChoice);
					}
				}

				switch (updateChoiceInt){
					case 1:
						System.out.println("Enter the new checkout date (YYYY-MM-DD):");
						String newCheckoutDate = keyboard.nextLine();

						// validate the date format using a regular expression
						if (!newCheckoutDate.matches("\\d{4}-\\d{2}-\\d{2}")) {
							throw new InvalidDateException("Invalid date format. Please enter the date in the format YYYY-MM-DD.");
						} else {
							sqlStmt = "UPDATE CHECKOUT SET CHECKOUTDATE = ? WHERE CHECKOUTID = ?";
							stmt = conn.prepareStatement(sqlStmt);
							stmt.setString(1, newCheckoutDate);
							stmt.setInt(2, checkoutID);
							stmt.executeUpdate();
						}
						break;
					case 2:
						System.out.println("Enter the new return date (YYYY-MM-DD):");
						String newReturnDate = keyboard.nextLine();

						// validate the date format using a regular expression
						if (!newReturnDate.matches("\\d{4}-\\d{2}-\\d{2}")) {
							throw new InvalidDateException("Invalid date format. Please enter the date in the format YYYY-MM-DD.");
						} else {
							// validate that the new return date is after the checkout date
							LocalDate checkoutDate = LocalDate.parse(resultSet.getString("CheckoutDate"));
							LocalDate returnDate = LocalDate.parse(newReturnDate);
							if (returnDate.isBefore(checkoutDate)) {
								throw new InvalidDateException("Return date cannot be before checkout date.");
							} else {
								sqlStmt = "UPDATE CHECKOUT SET RETURNDATE = ? WHERE CHECKOUTID = ?";
								stmt = conn.prepareStatement(sqlStmt);
								stmt.setString(1, newReturnDate);
								stmt.setInt(2, checkoutID);
								stmt.executeUpdate();
							}
						}
						break;
					case 3:
						System.out.println("Enter the new Member ID:");
						String newMemberID = keyboard.nextLine();

						// check if the member ID provided by the user exists in the database
						sqlStmt = "SELECT * FROM MEMBER WHERE MEMBERID = ?";
						stmt = conn.prepareStatement(sqlStmt);
						stmt.setString(1, newMemberID);
						ResultSet memberResultSet = stmt.executeQuery();
						if (!memberResultSet.next()) {
							throw new NotFoundException("Member not found. Please enter a valid Member ID.");
						} else {
							sqlStmt = "UPDATE CHECKOUT SET MEMBERID = ? WHERE CHECKOUTID = ?";
							stmt = conn.prepareStatement(sqlStmt);
							stmt.setString(1, newMemberID);
							stmt.setInt(2, checkoutID);
							stmt.executeUpdate();
						}
						break;
					case 4:
						System.out.println("Enter the new Book ISBN:");
						String newBookISBN = keyboard.nextLine();
						
						// check if the book ISBN provided by the user exists in the database
						sqlStmt = "SELECT * FROM BOOK WHERE ISBN = ?";
						stmt = conn.prepareStatement(sqlStmt);
						stmt.setString(1, newBookISBN);
						ResultSet bookResultSet = stmt.executeQuery();
						if (!bookResultSet.next()) {
							throw new NotFoundException("Book not found. Please enter a valid ISBN.");
						} else {
							sqlStmt = "UPDATE CHECKOUT SET BOOKISBN = ? WHERE CHECKOUTID = ?";
							stmt = conn.prepareStatement(sqlStmt);
							stmt.setString(1, newBookISBN);
							stmt.setInt(2, checkoutID);
							stmt.executeUpdate();
						}
						break;
					default:
						throw new NotFoundException("Invalid update choice.");
				}
				System.out.println("Checkout updated successfully.\n");
			}

		} catch (SQLException e) {
			System.out.println(e.getMessage());
			return;
		} catch (NotFoundException e) {
			System.out.println(e.getMessage());
			return;
		} catch (InvalidDateException e) {
			System.out.println(e.getMessage());
			return;
		}
	}

	/**
	 * Method to search through the different checkouts in the database
	 * The user can search through the checkouts by any of the checkout variables
	 * Returns all the data based on what the user is searching for ie:
	 * if the user is searching for things returning on a specific date, return all the checkouts with that return date
	 * if the user is searching for checkouts with a specific book ISBN, return all the checkouts with that book ISBN etc.
	 * If the user searches for a checkout that is not found in the database, display an error message and return to the menu
	 */
	@Override
	public void search() {
		try {
			System.out.println("Search menu: \n1) Search by Checkout Date \n2) Search by Return Date \n3) Search by Member ID \n4) Search by Book ISBN");
			int searchChoiceInt = 0;
			while (searchChoiceInt < 1 || searchChoiceInt > 4) {
				String searchChoice = keyboard.nextLine();
				if (!searchChoice.matches("[1-4]")) {
					System.out.println("Invalid input. Please enter a number between 1 and 4.");
					continue;
				} else {
					searchChoiceInt = Integer.parseInt(searchChoice);
				}
			}
			switch (searchChoiceInt){
				case 1:
					System.out.println("Enter the checkout date you want to search for (YYYY-MM-DD):");
					String searchCheckoutDate = keyboard.nextLine();
					
					// validate that user inputed date is a valid date
						if (!searchCheckoutDate.matches("\\d{4}-\\d{2}-\\d{2}")) {
							throw new InvalidDateException("Invalid date format. Please enter the date in the format YYYY-MM-DD.");
						} else {
							String sqlStmt = "SELECT * FROM CHECKOUT WHERE CHECKOUTDATE = ?";
							PreparedStatement stmt = conn.prepareStatement(sqlStmt);
							stmt.setString(1, searchCheckoutDate);
							ResultSet resultSet = stmt.executeQuery();
							boolean found = false;
							while (resultSet.next()) {
								found = true;
								System.out.println(String.format("Checkout ID: %s Checkout Date: %s Return Date: %s Member ID: %s Book ISBN: %s\n", resultSet.getInt("CheckoutID"), resultSet.getString("CheckoutDate"), resultSet.getString("ReturnDate"), resultSet.getString("MemberID"), resultSet.getString("BookISBN")));
							}
							if (!found) {
								throw new NotFoundException("No checkouts found with that checkout date.");
							}
						}
					break;
				case 2:
					System.out.println("Enter the return date you want to search for (YYYY-MM-DD):");
					String searchReturnDate = keyboard.nextLine();

					// validate that user inputed date is a valid date
						if (!searchReturnDate.matches("\\d{4}-\\d{2}-\\d{2}")) {
							throw new InvalidDateException("Invalid date format. Please enter the date in the format YYYY-MM-DD.");
						} else {
							String sqlStmt = "SELECT * FROM CHECKOUT WHERE RETURNDATE = ?";
							PreparedStatement stmt = conn.prepareStatement(sqlStmt);
							stmt.setString(1, searchReturnDate);
							ResultSet resultSet = stmt.executeQuery();
							boolean found = false;
							while (resultSet.next()) {
								found = true;
								System.out.println(String.format("Checkout ID: %s Checkout Date: %s Return Date: %s Member ID: %s Book ISBN: %s\n", resultSet.getInt("CheckoutID"), resultSet.getString("CheckoutDate"), resultSet.getString("ReturnDate"), resultSet.getString("MemberID"), resultSet.getString("BookISBN")));
							}
							if (!found) {
								throw new NotFoundException("No checkouts found with that return date.");
							}
						}
					break;
				case 3:
					System.out.println("Enter the Member ID for the member's checkouts you want to search for:");
					String searchMemberID = keyboard.nextLine();
					
					String sqlStmt = "SELECT * FROM CHECKOUT WHERE MEMBERID = ?";
					PreparedStatement stmt = conn.prepareStatement(sqlStmt);
					stmt.setString(1, searchMemberID);
					ResultSet resultSet = stmt.executeQuery();
					boolean found = false;
					while (resultSet.next()) {
						found = true;
						System.out.println(String.format("Checkout ID: %s Checkout Date: %s Return Date: %s Member ID: %s Book ISBN: %s\n", resultSet.getInt("CheckoutID"), resultSet.getString("CheckoutDate"), resultSet.getString("ReturnDate"), resultSet.getString("MemberID"), resultSet.getString("BookISBN")));
					}
					if (!found) {
						throw new NotFoundException("No checkouts found with that Member ID.");
					}
					break;
				case 4:
					System.out.println("Enter the Book ISBN for the checkout you want to search for:");
					String searchBookISBN = keyboard.nextLine();
					
					sqlStmt = "SELECT * FROM CHECKOUT WHERE BOOKISBN = ?";
					stmt = conn.prepareStatement(sqlStmt);
					stmt.setString(1, searchBookISBN);
					resultSet = stmt.executeQuery();
					found = false;
					while (resultSet.next()) {
						found = true;
						System.out.println(String.format("Checkout ID: %s Checkout Date: %s Return Date: %s Member ID: %s Book ISBN: %s\n", resultSet.getInt("CheckoutID"), resultSet.getString("CheckoutDate"), resultSet.getString("ReturnDate"), resultSet.getString("MemberID"), resultSet.getString("BookISBN")));
					}
					if (!found) {
						throw new NotFoundException("No checkouts found with that Book ISBN.");
					}
					break;
				default:
					throw new IllegalArgumentException("Invalid input.");
			}
		} catch (NotFoundException e) {
			System.out.println(e.getMessage());
			return;
		} catch (InvalidDateException e) {
			System.out.println(e.getMessage());
			return;
		} catch (SQLException e) {
			System.out.println(e.getMessage());
			return;
		} catch (IllegalArgumentException e) {
			System.out.println(e.getMessage());
			return;
		}
		
	}

	/**
	 * Method to view all the checkouts in the database
	 * Returns all the data for all the checkouts in the database and displays it in a readable format
	 * If there are no checkouts in the database, display a message saying there are no checkouts to display
	 */
	@Override
	public void viewAll() {
		String sqlStmt = "SELECT * FROM Checkout";
		try {
			PreparedStatement stmt = conn.prepareStatement(sqlStmt);
			ResultSet resultSet = stmt.executeQuery();
			boolean found = false;
			while (resultSet.next()) {
				found = true;
				System.out.println(String.format("Checkout ID: %s Checkout Date: %s Return Date: %s Member ID: %s Book ISBN: %s\n", resultSet.getInt("CheckoutID"), resultSet.getString("CheckoutDate"), resultSet.getString("ReturnDate"), resultSet.getString("MemberID"), resultSet.getString("BookISBN")));
			}
			if (!found) {
				System.out.println("No checkouts to display.");
			}
		} catch (SQLException e) {
			System.out.println(e.getMessage());
		}
	}
}
