package manager;

import java.sql.*;
import java.util.Scanner;

import errors.NotFoundException;
import errors.CharacterLimitException;

public class MemberManager extends Manager {

	/**
	 * Constructor to initialize the member manager by setting the super class variables for the database connection
	 */
	public MemberManager(Connection conn, Statement stmt) {
		super(conn, stmt);
	}

	/**
	 * Method to display the member manager menu and get a valid menu choice from the user
	 * the menu options are as follows:
	 * Add a new member from the database, remove a member from the database, update a members information
	 * search for a member in the database, view all members in the database, and return to the main menu
	 * if the user enters an invalid menu choice, an error message will be displayed and the menu will loop again 
	 */
	@Override
	public void displayMenu() {
		// Variable to hold the user's menu input and initialize the keyboard scanner created in the method abstract class
		int choice = 0;
		keyboard = new Scanner(System.in);
		// Loop menu options until the user chooses to exit the member manager
		while(choice != 6) {
			System.out.println("Member Manager Menu:");
			System.out.println("1) Add new member.");
			System.out.println("2) Search for a member.");
			System.out.println("3) Update existing member.");
			System.out.println("4) Remove existing member.");
			System.out.println("5) View all members.");
			System.out.println("6) Exit member manager.");

			// menu choice validation
			String choiceStr = keyboard.nextLine();
			while (!choiceStr.matches("[1-6]")) {
				System.out.println("Invalid input. Please enter a number between 1 and 6.");
				choiceStr = keyboard.nextLine();
			}

			choice = Integer.parseInt(choiceStr);
			switch(choice) {
				case 1: 
				try {
					add();
				} catch (Throwable e) {
					System.out.println(e.getMessage());
				}
					break;
				case 2:
					search();
					break;
				case 3:
				try {
					update();
				} catch (Throwable e) {
					System.out.println(e.getMessage());
				}
					break;
				case 4:
					remove();
					break;
				case 5:
					viewAll();
					break;
				case 6:
					System.out.println("Returning to main menu.");
					break;
				default:
					System.out.println("Invalid input. Please Enter 1 to 6.");	
			}
		}
	}

	/**
	 * Method to add a new member to the database
	 * the user will be prompted to enter the new members first and last name
	 * the member ID will be automatically generated by the database and will not be entered by the user
	 * if the first name or last name entered by the user is not valid, send error message
	 * if the member is successfully added to the database, a success message will be displayed to the user
	 */
	@Override
	public void add() {
		// ask for members first name and validate it
		System.out.println("Enter the new members first name:");
		String firstName = keyboard.nextLine();
		while (firstName.length() < 1 || firstName.length() > 50) {
			System.out.println("Invalid First Name. First Name must be between 1 and 50 characters long. Please enter a valid First Name:");
			firstName = keyboard.nextLine();
		}

		// ask for members last name and validate it
		System.out.println("Enter the new members last name:");
		String lastName = keyboard.nextLine();
		while (lastName.length() < 1 || lastName.length() > 50) {
			System.out.println("Invalid Last Name. Last Name must be between 1 and 50 characters long. Please enter a valid Last Name:");
			lastName = keyboard.nextLine();
		}

		try {
			String sqlStmt = "INSERT INTO MEMBER (FirstName, LastName) VALUES (?, ?)";
			PreparedStatement stmt = conn.prepareStatement(sqlStmt);
			stmt.setString(1, firstName);
			stmt.setString(2, lastName);
			stmt.executeUpdate();
			System.out.println("Member added successfully.");
		} catch (SQLException e) {
			e.printStackTrace();
		}
	}

	/**
	 * Method to remove a member from the database
	 * User will be prompted to enter the member ID of the member they want to remove
	 * if the member ID is not found in the database, an error message will be displayed to the user
	 * if the member ID is found, the member will be removed from the database
	 * if the member has any checkouts that have not been returned, an error message will be displayed and the member won't be deleted
	 * if the member is successfully removed, a success message will be displayed to the user
	 */
	@Override
	public void remove() {
		System.out.println("Enter the Member ID of the member being removed: ");
		String memberID = keyboard.nextLine();

		try {
			// validation to check if the member ID is found in the database
			String sqlStmt = "SELECT * FROM MEMBER WHERE MEMBERID = ?";

			PreparedStatement stmt = conn.prepareStatement(sqlStmt);
			stmt.setString(1, memberID);
			ResultSet resultSet = stmt.executeQuery();
			if (!resultSet.next()) {
				throw new NotFoundException("No member found with the given Member ID.");
			} else {
				// check to see if the member has any outstanding checkouts
				sqlStmt = "SELECT * FROM CHECKOUT WHERE MEMBERID = ?";
				stmt = conn.prepareStatement(sqlStmt);
				stmt.setString(1, memberID);
				resultSet = stmt.executeQuery();
				if (resultSet.next()) {
					throw new NotFoundException("Member with ID: " + memberID + " cannot be deleted because they have outstanding checkouts.");
				} else {
					sqlStmt = "DELETE FROM MEMBER WHERE MEMBERID = ?";
					stmt = conn.prepareStatement(sqlStmt);
					stmt.setString(1, memberID);
					stmt.executeUpdate();
					System.out.println("Member with ID: " + memberID + " was successfully removed.");
				}
			}
		} catch (SQLException e) {
			e.printStackTrace();
		} catch (NotFoundException e) {
			System.out.println(e.getMessage());
		}
	}

	/**
	 * Method to update a members information in the database
	 * the user will be prompted to enter the member ID of the member they want to update
	 * if the member ID is not found in the database, an error message will be displayed
	 * if the member ID is found, the current information of the member will be displayed to the user
	 * User will then be promted to enter the number corresponding to the information they want to update (first name, last name)
	 * the user will then be prompted to enter the new information for the member
	 * if the new information is not valid, an error message will be displayed to the user
	 * if the member has any current checkouts, an error message will be displayed and member won't update
	 */
	@Override
	public void update() {
		System.out.println("Enter the Member ID of the member you want to update:");
		String memberID = keyboard.nextLine();
		try {
			String sqlStmt = "SELECT * FROM MEMBER WHERE MEMBERID = ?";
			PreparedStatement stmt = conn.prepareStatement(sqlStmt);
			stmt.setString(1, memberID);
			ResultSet resultSet = stmt.executeQuery();
			if (!resultSet.next()) {
				throw new NotFoundException("No member found with the given Member ID.");
			} else {
				// check to see if the member has any checkouts that have not been returned
				sqlStmt = "SELECT * FROM CHECKOUT WHERE MEMBERID = ?";
				stmt = conn.prepareStatement(sqlStmt);
				stmt.setString(1, memberID);
				ResultSet resultSet2 = stmt.executeQuery();
				if (resultSet2.next()) {
					throw new NotFoundException("Member with ID: " + memberID + " cannot be updated because they have outstanding checkouts.");
				} else {
					// print out the current information of the member to the user
					System.out.println(String.format("Current Information for Member ID: %s \nFirst Name: %s Last Name: %s\n", resultSet.getString("MemberID"), resultSet.getString("FirstName"), resultSet.getString("LastName")));
				
					// get a valid menu choice from the user
					System.out.println("Enter the number corresponding to the information you want to update: \n1) First Name \n2) Last Name");
					int menuChoice = 0;
					while (menuChoice < 1 || menuChoice > 2) {
						menuChoice = Integer.parseInt(keyboard.nextLine());
						if (menuChoice < 1 || menuChoice > 2) {
							System.out.println("Invalid menu choice. Please enter a number between 1 and 2.");
						}
					}
					switch (menuChoice) {
						// Case for updating the first name
						case 1:
							System.out.println("Enter the new First Name:");
							String firstName = keyboard.nextLine();
	
							// first name validation, first name must be between 1 and 50 characters long
							if (firstName.length() < 1 || firstName.length() > 50) {
								throw new CharacterLimitException("Invalid First Name. First Name must be between 1 and 50 characters long.");
							} else {
								String updateStmt = "UPDATE MEMBER SET FIRSTNAME = ? WHERE MEMBERID = ?";
								PreparedStatement update = conn.prepareStatement(updateStmt);
								update.setString(1, firstName);
								update.setString(2, memberID);
								update.executeUpdate();
								System.out.println("First Name updated successfully.");
							}
							break;
						// Case for updating the last name
						case 2:
							System.out.println("Enter the new Last Name:");
							String lastName = keyboard.nextLine();
	
							// last name validation, last name must be between 1 and 50 characters long
							if (lastName.length() < 1 || lastName.length() > 50) {
								throw new CharacterLimitException("Invalid Last Name. Last Name must be between 1 and 50 characters long.");
							} else {
								String updateStmt = "UPDATE MEMBER SET LASTNAME = ? WHERE MEMBERID = ?";
								PreparedStatement update = conn.prepareStatement(updateStmt);
								update.setString(1, lastName);
								update.setString(2, memberID);
								update.executeUpdate();
								System.out.println("Last Name updated successfully.");
							}
							break;
						default:
							throw new IllegalArgumentException("Invalid menu choice.");
					}
				}
			}
		} catch (SQLException e) {
			e.printStackTrace();
		} catch (NotFoundException e) {
			System.out.println(e.getMessage());
		} catch (CharacterLimitException e) {
			System.out.println(e.getMessage());
		}
	}

	/**
	 * Method to search for a member in the database
	 * the user will be prompted to enter either the members ID, first name, or last name
	 * The method will then search the database for members that match the search criteria
	 * if no members are found, an error message will be displayed to the user
	 * if the information entered by the user is not valid, an error message will be displayed to the user
	 */
	@Override
	public void search() {
		int menuChoice = 0;
		System.out.println("Search menu: \n1) Search by Member ID \n2) Search by First Name \n3) Search by Last Name");
		
		// get a valid menu choice from the user
		String menuChoiceStr = keyboard.nextLine();
		while (!menuChoiceStr.matches("[1-3]")) {
			System.out.println("Invalid menu choice. Please enter 1, 2, or 3.");
			menuChoiceStr = keyboard.nextLine();
		}
		menuChoice = Integer.parseInt(menuChoiceStr);


		switch (menuChoice) {
			// Selecting the serch criteria by member id
			case 1:
				System.out.println("Enter the Member ID to search for:");
				String memberID = keyboard.nextLine();
				try {
					String sqlStmt = "SELECT * FROM MEMBER WHERE MEMBERID = ?";
					PreparedStatement stmt = conn.prepareStatement(sqlStmt);
					stmt.setString(1, memberID);
					ResultSet resultSet = stmt.executeQuery();
					boolean found = false;
					while (resultSet.next()) {
						found = true;
						System.out.println(String.format("Member ID: %s First Name: %s Last Name: %s\n", resultSet.getString("MemberID"), resultSet.getString("FirstName"), resultSet.getString("LastName")));
					}
					if (!found) {
						throw new NotFoundException("No members found with the given Member ID.");
					}
				} catch (SQLException e) {
					e.printStackTrace();
				} catch (NotFoundException e) {
					System.out.println(e.getMessage());
				}
				break;
			// Selecting the search criteria by first name
			case 2:
				System.out.println("Enter the First Name to search for:");
				String firstName = keyboard.nextLine();
				
				try {
					// check if the first name is valid, it must be between 1 and 50 characters long
					if (firstName.length() < 1 || firstName.length() > 50) {
						throw new CharacterLimitException("Invalid First Name. First Name must be between 1 and 50 characters long.");
					} else {
							// if first name is valid search the database for members with the given first name
							String sqlStmt = "SELECT * FROM MEMBER WHERE FIRSTNAME = ?";
							PreparedStatement stmt = conn.prepareStatement(sqlStmt);
							stmt.setString(1, firstName);
							ResultSet resultSet = stmt.executeQuery();
							boolean found = false;
							while (resultSet.next()) {
								found = true;
								System.out.println(String.format("Member ID: %s First Name: %s Last Name: %s\n", resultSet.getString("MemberID"), resultSet.getString("FirstName"), resultSet.getString("LastName")));
							}
							if (!found) {
								throw new NotFoundException("No members found with the given First Name.");
							}
					} 
				} catch (CharacterLimitException e) {
					System.out.println(e.getMessage());
				} catch (SQLException e) {
					e.printStackTrace();
				} catch (NotFoundException e) {
					System.out.println(e.getMessage());
				}
				break;
			// Selecting the search criteria by last name
			case 3:
				System.out.println("Enter the Last Name to search for:");
				String lastName = keyboard.nextLine();

				try {
					// check if the last name is valid, it must be between 1 and 50 characters long
					if (lastName.length() < 1 || lastName.length() > 50) {
						throw new CharacterLimitException("Invalid Last Name. Last Name must be between 1 and 50 characters long.");
					} else {
							// if last name is valid search the database for members with the given last name
							String sqlStmt = "SELECT * FROM MEMBER WHERE LASTNAME = ?";
							PreparedStatement stmt = conn.prepareStatement(sqlStmt);
							stmt.setString(1, lastName);
							ResultSet resultSet = stmt.executeQuery();
							boolean found = false;
							while (resultSet.next()) {
								found = true;
								System.out.println(String.format("Member ID: %s First Name: %s Last Name: %s\n", resultSet.getString("MemberID"), resultSet.getString("FirstName"), resultSet.getString("LastName")));
							}
							if (!found) {
								throw new NotFoundException("No members found with the given Last Name.");
							}
					} 
				} catch (CharacterLimitException e) {
					System.out.println(e.getMessage());
				} catch (SQLException e) {
					e.printStackTrace();
				} catch (NotFoundException e) {
					System.out.println(e.getMessage());
				}
				break;
			default:
				throw new IllegalArgumentException("Invalid menu choice.");
			}

	}

	/**
	 * Method to view all members in the database and display their information to the user
	 * if there are no members in the database, error out and a message will be displayed to the user
	 * if there are members in the database, display their member ID, first name, and last name
	 * the information will be displayed in a formatted manner for the user to read
	 */
	@Override
	public void viewAll() {
		try {
			String sqlStmt = "SELECT * FROM MEMBER";
			ResultSet resultSet = stmt.executeQuery(sqlStmt);
			boolean found = false;
			while (resultSet.next()) {
				found = true;
				System.out.println(String.format("Member ID: %s First Name: %s Last Name: %s\n", resultSet.getString("MemberID"), resultSet.getString("FirstName"), resultSet.getString("LastName")));
			}
			if (!found) {
				throw new NotFoundException("No members to display.");
			}
		} catch (SQLException e) {
			e.printStackTrace();
		} catch (NotFoundException e) {
			System.out.println(e.getMessage());
		}
	}

}
